config/routes.rb
Rails.application.routes.draw do
  resources :saved_filters, only: [:destroy]
  resources :expenses, only: [:create, :index, :destroy]
  resources :invoices, only: [:create, :index]
  resource :pay_rate, only: [:show, :new, :create]
  resources :exports, only: [:create]
  resources :logs, only: [:index, :create, :edit, :update, :destroy]
  resources :projects, only: [:index, :new, :create, :edit, :update]
  resources :clients, only: [:index, :new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/dashboard" => "dashboard#index"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  root "home#index"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :load_and_save_filters

  def index
    @start_date = params[:filtered_start_date]&.to_date || (Date.today.beginning_of_month)
    @end_date = params[:filtered_end_date]&.to_date&.end_of_day || Date.today.end_of_month
    @all_logs = Log.where(active: true).in_datetime_range(@start_date.in_time_zone(TIMEZONE).beginning_of_day, @end_date.in_time_zone(TIMEZONE).end_of_day)
    @all_logs = @all_logs.where(project_id: params[:filtered_project]) if params[:filtered_project].present?
    @logs = @all_logs.page(params[:page]).ordered.per(50)
  end
end

app/views/dashboard/index.html.erb
<div class="columns">
  <div class="column">
    <h1 class="title"><%= icon("tachometer-alt") %> Dashboard</h1>
    <div style="margin-bottom: 1.5rem">
      <% if current_log %>
        <%= link_to icon("pencil-alt", "Finish Current Log"), edit_log_path(current_log), class: "button is-warning" %>
      <% else %>
        <%= link_to icon("plus-circle", "Start New Log"), logs_path, method: :post, class: "button is-primary" %>
      <% end %>
      <%= button_tag icon("file-export", "Export Hours (CSV)"), class: "button is-primary", id: "export-modal-trigger" %>

      <div class="modal" id="export-modal">
        <div class="modal-background"></div>
        <div class="modal-content">
          <div class="box">
            <%= form_tag exports_path(format: :csv), method: :post do %>
              <div>
                <label class="label">Date Range</label>
                <div class="field has-addons">
                  <div class="control has-icons-left">
                    <%= date_field_tag :start_date, input_date(1.week.ago.beginning_of_week), required: true, class: "input is-medium date-input", pattern: "[0-9]{2}/[0-9]{2}/[0-9]{4}", placeholder: "Start Date" %>
                    <span class="icon is-left">
                      <i class="fas fa-calendar fa-sm"></i>
                    </span>
                  </div>
                  <div class="control has-icons-left">
                    <%= date_field_tag :end_date, input_date(1.week.ago.end_of_week - 1.day), required: true, class: "input is-medium date-input", pattern: "[0-9]{2}/[0-9]{2}/[0-9]{4}", placeholder: "End Date" %>
                    <span class="icon is-left">
                      <i class="fas fa-calendar fa-sm"></i>
                    </span>
                  </div>
                </div>

                <div class="field">
                  <label class="label">Client</label>
                  <div class="select">
                    <%= select_tag :client_id, options_from_collection_for_select(Client.alphabetized.unarchived, :id, :name, Client.first&.id), include_blank: "All" %>
                  </div>
                </div>

                <div class="field">
                  <label class="label">Project</label>
                  <div class="select">
                    <%= select_tag :project_id, options_from_collection_for_select(Project.alphabetized.unarchived, :id, :name), include_blank: "All" %>
                  </div>
                </div>

                <div class="field">
                  <div class="control">
                    <%= button_tag icon("file-export", "Export Hours From Dates"), class: "button is-primary", type: :submit %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <button class="modal-close is-large" aria-label="close"></button>
      </div>
    </div>
  </div>

  <div class="column">
    <canvas id="chart" style="width: 100%; height: 120px;" data-values="<%= hours_by_weeks(5).to_json %>"></canvas>
  </div>
</div>

<div class="columns">
  <div class="column is-narrow">
    <div class="box">
      <span class="title is-4"><%= pluralize(number_with_precision((@all_logs.map(&:elapsed_seconds).inject(:+) || 0) / 60.0 / 60, strip_insignificant_zeros: true, precision: 2), "Hour") %> <span class="has-text-warning">Filtered</span></span>
    </div>
  </div>

  <div class="column is-narrow">
    <div class="box">
      <span class="title is-4"><%= pluralize(number_with_precision((Log.where(active: true).in_datetime_range(Date.today.in_time_zone(TIMEZONE).beginning_of_day, Date.today.in_time_zone(TIMEZONE).end_of_day).map(&:elapsed_seconds).inject(:+) || 0) / 60.0 / 60, strip_insignificant_zeros: true, precision: 2), "Hour") %> <span class="has-text-success">Today</span></span>
    </div>
  </div>

  <div class="column">
    <div class="box">
      <span class="title is-4"><%= pluralize(number_with_precision(Log.current_pay_period_elapsed_seconds / 60.0 / 60, strip_insignificant_zeros: true, precision: 2), "Hour") %> <span class="has-text-info">This Pay Period</span></span>
      <small><%= Log.current_pay_period_dates.min.strftime("%b %e, %Y") %> - <%= Log.current_pay_period_dates.max.strftime("%b %e, %Y") %></small>
    </div>
  </div>
</div>

<div class="block">
  <%= form_tag dashboard_path, method: :get do %>
    <div class="columns">
      <div class="column is-one-half">
        <label class="label">Date Range</label>
        <div class="field has-addons">
          <div class="control is-expanded has-icons-left">
            <%= date_field_tag :filtered_start_date, input_date(@start_date), required: true, class: "input is-medium date-input", pattern: "[0-9]{2}/[0-9]{2}/[0-9]{4}", placeholder: "Start Date" %>
            <span class="icon is-left">
              <i class="fas fa-calendar fa-sm"></i>
            </span>
          </div>
          <div class="control is-expanded has-icons-left">
            <%= date_field_tag :filtered_end_date, input_date(@end_date), required: true, class: "input is-medium date-input", pattern: "[0-9]{2}/[0-9]{2}/[0-9]{4}", placeholder: "End Date" %>
            <span class="icon is-left">
              <i class="fas fa-calendar fa-sm"></i>
            </span>
          </div>
        </div>
      </div>

      <div class="column is-one-quarter">
        <%= label_tag :filtered_project, "Project", class: "label" %>
        <div class="field">
          <div class="control is-expanded">
            <div class="select is-medium">
              <%= select_tag :filtered_project, options_from_collection_for_select(Project.unarchived, :id, :name, params[:filtered_project]), include_blank: "All" %>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-one-quarter">
        <div class="field">
          <label class="label">&nbsp;</label>
          <div class="control">
            <%= button_tag icon("search", "Search Logs"), class: "button is-primary is-fullwidth", type: :submit %>
            <% if @filter.present? && @filter.filters.present? %>
              <%= link_to icon("times", "Clear Filters"), saved_filter_path(@filter), method: :delete, class: "has-text-warning is-size-7 has-text-weight-bold" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<table class="table" style="width: 100%;">
  <thead>
    <tr>
      <th style="text-align: center">Active</th>
      <th>Start</th>
      <th>End</th>
      <th>Hours</th>
      <th>Project</th>
      <th>Description</th>
      <th style="text-align: center;" colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% Log.where(active: false).ordered.each do |inactive_log| %>
      <%= render "logs/log", log: inactive_log %>
    <% end %>
    <% @logs.each do |log| %>
      <%= render "logs/log", log: log %>
    <% end %>
  </tbody>
</table>

<%= paginate @logs %>