config/routes.rb
Rails.application.routes.draw do
  resources :saved_filters, only: [:destroy]
  resources :expenses, only: [:create, :index, :destroy]
  resources :invoices, only: [:create, :index]
  resource :pay_rate, only: [:show, :new, :create]
  resources :exports, only: [:create]
  resources :logs, only: [:index, :create, :edit, :update, :destroy]
  resources :projects, only: [:index, :new, :create, :edit, :update]
  resources :clients, only: [:index, :new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/dashboard" => "dashboard#index"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  root "home#index"
end

app/models/client.rb
class Client < ApplicationRecord
  validates :name, presence: true, uniqueness: {case_sensitive: false}

  scope :alphabetized, -> { order("clients.name ASC") }
  scope :unarchived, -> { where(archived_at: nil) }

  def archived=(status)
    status = status == 'true' if status.is_a?(String)

    if status
      self.archived_at ||= Time.now
    else
      self.archived_at = nil
    end
  end

  def archived?
    archived_at?
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.order("name ASC")
  end

  def new
  end

  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to clients_path, notice: "Successfully created new client!" }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to clients_path, notice: "Successfully updated client!" }
      else
        format.html { render :edit }
      end
    end
  end

  private

    def client_params
      params.require(:client).permit(:name, :archived)
    end
end

app/views/clients/_form.html.erb
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><%= link_to "Clients", clients_path %></li>
    <li class="is-active"><a href="#" aria-current="page"><%= params[:action].titleize %> Client</a></li>
  </ul>
</nav>

<h1 class="title"><%= params[:action].titleize %> Client</h1>

<%= form_for client do |f| %>
  <div class="field">
    <%= f.label :name %>
    <div class="control">
      <%= f.text_field :name, class: "input" %>
    </div>
  </div>

  <div>
    <%= f.submit class: "button is-primary" %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<%= render "form", client: @client %>

app/views/clients/index.html.erb
<h1 class="title">Clients</h1>

<%= link_to icon("plus-circle", "New Client"), new_client_path, class: "button is-primary" %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th class="has-text-centered" colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <tr style="<%= 'opacity: 0.5' if client.archived? %>">
        <td><%= client.name %></td>
        <td><%= link_to "Edit", edit_client_path(client) %></td>
        <td><%= link_to "#{client.archived? ? 'Una' : 'A'}rchive", client_path(client, client: {archived: !client.archived?}), method: :patch %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clients/new.html.erb
<%= render "form", client: Client.new %>