config/routes.rb
Rails.application.routes.draw do
  resources :saved_filters, only: [:destroy]
  resources :expenses, only: [:create, :index, :destroy]
  resources :invoices, only: [:create, :index]
  resource :pay_rate, only: [:show, :new, :create]
  resources :exports, only: [:create]
  resources :logs, only: [:index, :create, :edit, :update, :destroy]
  resources :projects, only: [:index, :new, :create, :edit, :update]
  resources :clients, only: [:index, :new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/dashboard" => "dashboard#index"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  root "home#index"
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true

  scope :alphabetized, -> { order("projects.name ASC") }
  scope :unarchived, -> { where(archived_at: nil) }

  def archived=(status)
    status = status == 'true' if status.is_a?(String)

    if status
      self.archived_at ||= Time.now
    else
      self.archived_at = nil
    end
  end

  def archived?
    archived_at?
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.order("name ASC")
  end

  def new
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: "Successfully created new project!" }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: "Successfully updated project!" }
      else
        format.html { render :edit }
      end
    end
  end

  private

    def project_params
      params.require(:project).permit(:name, :short_name, :archived, :client_id)
    end
end

app/views/projects/_form.html.erb
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><%= link_to "Projects", projects_path %></li>
    <li class="is-active"><a href="#" aria-current="page"><%= params[:action].titleize %> Project</a></li>
  </ul>
</nav>

<h1 class="title"><%= params[:action].titleize %> Project</h1>

<%= form_for project do |f| %>
  <div class="field">
    <%= f.label :name %>
    <div class="control">
      <%= f.text_field :name, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :short_name %>
    <div class="control">
      <%= f.text_field :short_name, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :client_id %>
    <div class="control">
      <%= f.select :client_id, options_from_collection_for_select(Client.alphabetized, :id, :name, project.client_id), {include_blank: "Please Select"}, class: "input" %>
    </div>
  </div>

  <div>
    <%= f.submit class: "button is-primary" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%= render "form", project: @project %>

app/views/projects/index.html.erb
<h1 class="title">Projects</h1>

<%= link_to icon("plus-circle", "New Project"), new_project_path, class: "button is-primary" %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Short</th>
      <th class="has-text-centered" colspan="2">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr style="<%= 'opacity: 0.5' if project.archived? %>">
        <td><%= project.name %></td>
        <td><%= project.short_name %></td>
        <td><%= link_to "Edit", edit_project_path(project) %></td>
        <td><%= link_to "#{project.archived? ? 'Una' : 'A'}rchive", project_path(project, project: {archived: !project.archived?}), method: :patch %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<%= render "form", project: Project.new %>