config/routes.rb
Rails.application.routes.draw do
  resources :saved_filters, only: [:destroy]
  resources :expenses, only: [:create, :index, :destroy]
  resources :invoices, only: [:create, :index]
  resource :pay_rate, only: [:show, :new, :create]
  resources :exports, only: [:create]
  resources :logs, only: [:index, :create, :edit, :update, :destroy]
  resources :projects, only: [:index, :new, :create, :edit, :update]
  resources :clients, only: [:index, :new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/dashboard" => "dashboard#index"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  root "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubatime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag "favicon.ico" %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
  </head>

  <body data-current-log="<%= current_log.present? %>">
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to icon("clock", "Rubatime"), root_path, class: "navbar-item" %>
        <a role="button" class="navbar-burger" data-target="nav-menu" aria-label="menu" aria-expanded="false">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>


      <div class="navbar-menu" id="nav-menu">
        <% if signed_in? %>
          <div class="navbar-item <%= 'is-active' if current_page?(controller: 'dashboard', action: 'index') %>"><%= link_to "Dashboard", dashboard_path %></div>
          <div class="navbar-item <%= 'is-active' if current_page?(controller: 'projects', action: 'index') %>"><%= link_to "Projects", projects_path %></div>
          <div class="navbar-item <%= 'is-active' if current_page?(controller: 'pay_rates', action: 'show') %>"><%= link_to "Pay Rate", pay_rate_path %></div>
          <div class="navbar-item <%= 'is-active' if current_page?(controller: 'invoices', action: 'index') %>"><%= link_to "Invoices", invoices_path %></div>
          <div class="navbar-item <%= 'is-active' if current_page?(controller: 'expenses', action: 'index') %>"><%= link_to "Expenses", expenses_path %></div>
          <div class="navbar-item <%= 'is-active' if current_page?(controller: 'projects', action: 'index') %>"><%= link_to "Clients", clients_path %></div>
          <div class="navbar-item"><%= link_to "Log Out", logout_path, method: :delete %></div>
        <% else %>
          <div class="navbar-item <%= 'is-active' if current_page?(controller: 'sessions', action: 'new') %>"><%= link_to "Log In", login_path %></div>
        <% end %>
      </div>
    </nav>

    <% flash.each do |type, msg| %>
      <div class="flash <%= 'is-success' if type == 'notice' %><%= 'is-danger' if type == 'alert' %> notification">
        <button class="delete" onclick="this.parentNode.remove();"></button>
        <%= msg %>
      </div>
    <% end %>

    <section class="section">
      <div class="container">
        <%= yield %>
      </div>
    </section>
  </body>
</html>